### ISSUE TITLE
does not work with tomcat

### ISSUE THREAD

**Issue by Tokhtar** [jfillo/spring-websocket-chatroom-angularjs#1]
Hello.
I copied the file spring-websocket-chatroom-angularjs.war of spring-websocket-chatroom-angularjs-master/target in apache-tomcat-8.0.9/webapps. 
Then launched starup tomcat
Then http://localhost:8080/spring-websocket-chatroom-angularjs/index.html
The website does not work properly.
The chat does not work properly.
Why?
![1](https://cloud.githubusercontent.com/assets/7579518/3668355/bf6b82ea-121a-11e4-963f-d520cfb9a451.jpg)

**Comment by jfillo** [comment]
Try deploying the application to the following Application Context:
http://localhost:8080/spring-chatroom

OR

Modify src\main\webapp\resources\js\controllers.js , line 11 - changing

```
$scope.client = ngstomp('/spring-chatroom/chatroom');
```

to

```
$scope.client = ngstomp('/spring-websocket-chatroom-angularjs/chatroom');
```

in order to match your application context.
